# Generated by Django 3.2.5 on 2021-11-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20211122_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='attachment',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
