# Generated by Django 3.2.5 on 2021-11-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_submissions_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='input1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='assignment',
            name='input2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='assignment',
            name='input3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_assignment_auto_judge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='output1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='assignment',
            name='output2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='assignment',
            name='output3',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
