# Generated by Django 3.2.5 on 2021-11-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20211126_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
