# Generated by Django 3.2.5 on 2021-11-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_submissions_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='language',
            field=models.IntegerField(blank=True, default=52),
        ),
    ]
