# Generated by Django 3.2.5 on 2021-11-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_submissions_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_group_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
